"""Initial schema

Revision ID: c4739f1cab3b
Revises: 
Create Date: 2026-02-05 18:15:10.227399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4739f1cab3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_template_name'), 'templates', ['template_name'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_tool_name'), 'tools', ['tool_name'], unique=False)
    op.create_table('facebook_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_profiles_profile_name'), 'facebook_profiles', ['profile_name'], unique=False)
    op.create_index(op.f('ix_facebook_profiles_template_id'), 'facebook_profiles', ['template_id'], unique=False)
    op.create_table('founders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('founder_name', sa.String(length=255), nullable=False),
    sa.Column('social_profile_url', sa.String(length=500), nullable=True),
    sa.Column('tool_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_founders_founder_name'), 'founders', ['founder_name'], unique=False)
    op.create_index(op.f('ix_founders_tool_id'), 'founders', ['tool_id'], unique=False)
    op.create_table('outreach_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('founder_id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('fb_profile_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('generated_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('MESSAGE_GENERATED', 'MESSAGE_SENT', 'REPLIED', 'CLOSED', 'GIVEAWAY_RUNNING', name='outreachstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fb_profile_id'], ['facebook_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['founder_id'], ['founders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_records_fb_profile_id'), 'outreach_records', ['fb_profile_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_founder_id'), 'outreach_records', ['founder_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_status'), 'outreach_records', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_records_template_id'), 'outreach_records', ['template_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_tool_id'), 'outreach_records', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_records_tool_id'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_template_id'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_status'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_founder_id'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_fb_profile_id'), table_name='outreach_records')
    op.drop_table('outreach_records')
    op.drop_index(op.f('ix_founders_tool_id'), table_name='founders')
    op.drop_index(op.f('ix_founders_founder_name'), table_name='founders')
    op.drop_table('founders')
    op.drop_index(op.f('ix_facebook_profiles_template_id'), table_name='facebook_profiles')
    op.drop_index(op.f('ix_facebook_profiles_profile_name'), table_name='facebook_profiles')
    op.drop_table('facebook_profiles')
    op.drop_index(op.f('ix_tools_tool_name'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_templates_template_name'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
