"""Add source_url and note fields

Revision ID: ddfe42834cd8
Revises: c4739f1cab3b
Create Date: 2026-02-05 18:49:30.683397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfe42834cd8'
down_revision: Union[str, Sequence[str], None] = 'c4739f1cab3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreach_records', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('tools', sa.Column('source_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'source_url')
    op.drop_column('outreach_records', 'note')
    # ### end Alembic commands ###
